var num=0;

imgArray = [
  ['Images/TripReports/Lembeh/This-is-Muck-Diving.jpg',' ',
   'Unlike diving a beautiful coral wall, muck diving is all about scouring the ocean floor to discover its many, magical residents. Here we have a lovely Clark Anemonefish (cousin of Nemo), two Porcelain Crabs, and a discarded water bottle. This is muck diving.'],
  ['Images/TripReports/Lembeh/Anemone.jpg',' ', 
  'Anemone'],
   
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  ['Images/TripReports/Lembeh/Anemone-Close-Up.jpg',' ',
  'Anemone Close Up'],
  ['Images/TripReports/Lembeh/Anemone-Crab.jpg',' ',
   'Anemone Crab'],
  ['Images/TripReports/Lembeh/Blue-Tunicates.jpg',' ', 
  'Blue Tunicates'],
  ['Images/TripReports/Lembeh/Bulb-Tunicates.jpg',' ', 
  'Bulb Tunicates'],
  ['Images/TripReports/Lembeh/Camoflauged-on-Red-Coral.jpg',' ', 
  'Camoflauged on Red Coral'],
  ['Images/TripReports/Lembeh/Chromodoris.jpg',' ',
   'Nudibranch-Chromodoris-kuniei - Nudibranchs are marine gastropods that have a shell-less and often beautifully colored body. Usually an inch or so in length, they range from barely visible to the 5-inch Solar Power Nudibranch.'],
  ['Images/TripReports/Lembeh/Chromodoris-annae.jpg',' ',
   'Chromodoris-annae'],
  ['Images/TripReports/Lembeh/Chromodoris-fidelis.jpg',' ',
   'Chromodoris-fidelis'],
  ['Images/TripReports/Lembeh/Chromodoris-magnifica.jpg',' ',
   'Chromodoris-magnifica'],
  ['Images/TripReports/Lembeh/Cleaner-Shrimp2xx.jpg',' ',
   'Cleaner-Shrimp'],
  ['Images/TripReports/Lembeh/Cleaner-Shrimp-with-Eggs.jpg',' ',
   'Cleaner-Shrimp-with-Eggs'],
  ['Images/TripReports/Lembeh/Coconut-Octopus2xx.jpg',' ',
   'Coconut-Octopus'],
  ['Images/TripReports/Lembeh/Crab-on-Sea-Cucumber.jpg',' ',
   'Crab-on-Sea-Cucumber'],
  ['Images/TripReports/Lembeh/Coral-Creations.jpg',' ', 
  'Coral Creations'],
  ['Images/TripReports/Lembeh/Coral-Disk.jpg',' ', 
  'Coral Disk'],
  ['Images/TripReports/Lembeh/Crinoid-2.jpg',' ', 
  'Crinoid 2'],
  ['Images/TripReports/Lembeh/Crinoid-Macro.jpg',' ', 
  'Crinoid Macro'],
  ['Images/TripReports/Lembeh/Crinoid-Macro.jpg',' ', 
  'Crinoid Macro'],
  ['Images/TripReports/Lembeh/Crinoid-Scene.jpg',' ', 
  'Crinoid Scene'],
  ['Images/TripReports/Lembeh/Crinoid-Tunicate-Scene.jpg',' ', 
  'Crinoid Tunicate Scene'],
  ['Images/TripReports/Lembeh/Cushion-Starfish.jpg',' ',
   'Cushion-Starfish'],
  ['Images/TripReports/Lembeh/Featherduster-Close-Up.jpg',' ', 
  'Featherduster Close Up'],
  ['Images/TripReports/Lembeh/Featherduster-Worm-Macro.jpg',' ', 
  'Featherduster Worm Macro'],
  ['Images/TripReports/Lembeh/Fire-Urchin2xx.jpg',' ',
   'Fire-Urchin'],
  ['Images/TripReports/Lembeh/Fire-Urchin-2.jpg',' ', 
  'Fire Urchin 2'],
  ['Images/TripReports/Lembeh/Flabellina-exoptata.jpg',' ',
   'Flabellina-exoptata'],
  ['Images/TripReports/Lembeh/Flowers-of-the-Sea.jpg',' ', 
  'Flowers of the Sea'],
  ['Images/TripReports/Lembeh/Friendly-Cuttlefish.jpg',' ', 
  'Friendly Cuttlefish'],
  ['Images/TripReports/Lembeh/Galletea-Elegans-Squat-Lobs.jpg',' ',
   'Galletea-Elegans-Squat-Lobster'],
  ['Images/TripReports/Lembeh/Golden-Cuttlefish.jpg',' ', 
  'Golden-Cuttlefish'],
  ['Images/TripReports/Lembeh/Green-Anemone.jpg',' ', 
  'Green Anemone'],
  ['Images/TripReports/Lembeh/Green-Anemone-Macro.jpg',' ', 
  'Green Anemone Macro'],
  ['Images/TripReports/Lembeh/Hairy-Squat-Lobster.jpg',' ', 
  'Hairy Squat Lobster'],
  ['Images/TripReports/Lembeh/Halgerda-batangas-Pattern.jpg',' ',
   'Halgerda-batangas-Pattern'],
  ['Images/TripReports/Lembeh/Halgerda-okinawa.jpg',' ',
   'Halgerda-okinawa'],
  ['Images/TripReports/Lembeh/Halgerda-okinawa-2.jpg',' ',
   'Halgerda-okinawa-2'],
  ['Images/TripReports/Lembeh/Halimeda-Crab.jpg',' ',
   'When sitting on a Halimeda Plant, this crab is nearly undetectable.'],
  ['Images/TripReports/Lembeh/Harlequin-Shrimp2xx.jpg',' ',
   'Harlequin-Shrimp'],
  ['Images/TripReports/Lembeh/Harlequin-Shrimp-Pair.jpg',' ',
   'Harlequin-Shrimp-Pair'],
  ['Images/TripReports/Lembeh/Hermit-Crab-2.jpg',' ', 
  'Hermit Crab 2'],
  ['Images/TripReports/Lembeh/Hypselodoris.jpg',' ', 
  'Hypselodoris'],
  ['Images/TripReports/Lembeh/Janolus.jpg',' ', 
  'Janolus'],
  ['Images/TripReports/Lembeh/Jorunna-parva.jpg',' ',
   'Jorunna-parva'],
  ['Images/TripReports/Lembeh/Mantis-Shrimp2xx.jpg',' ',
   'Mantis-Shrimp'],
  ['Images/TripReports/Lembeh/Mantis-Shrimp-With-Eggs2xx.jpg',' ',
   'Mantis-Shrimp-With-Eggs'],
  ['Images/TripReports/Lembeh/Map-Puffer-2.jpg',' ', 
  'Map Puffer 2'],
  ['Images/TripReports/Lembeh/Mexichromis-mariei.jpg',' ', 
  'Mexichromis-mariei'],
  ['Images/TripReports/Lembeh/Mixed-Tunicates.jpg',' ', 
  'Mixed-Tunicates'],
  ['Images/TripReports/Lembeh/Nembrotha.jpg',' ',
   'Nembrotha'],
  ['Images/TripReports/Lembeh/Nembrotha-2.jpg',' ', 
  'Nembrotha 2'],
  ['Images/TripReports/Lembeh/Napoleon-Snake-Eel-2.jpg',' ', 
  'Napoleon Snake Eel 2'],
  ['Images/TripReports/Lembeh/One-Inch-Pgymy-Cuttlefish-.jpg',' ',
   'One-Inch-Pgymy-Cuttlefish'],
  ['Images/TripReports/Lembeh/Pygmy-Cuttlefish.jpg',' ',
   'Pygmy-Cuttlefish'],
  ['Images/TripReports/Lembeh/Phyllidia-Blue-Dragon.jpg',' ', 
  'Phyllidia Blue Dragon'],
  ['Images/TripReports/Lembeh/Phyllodesmium-parangatum.jpg',' ', 
  'Phyllodesmium parangatum'],
  ['Images/TripReports/Lembeh/Porcelain-Crab-2.jpg',' ', 
  'Porcelain Crab 2'],
  ['Images/TripReports/Lembeh/Procelain-Crab.jpg',' ', 
  'Procelain Crab'],
  ['Images/TripReports/Lembeh/Red-Anemone.jpg',' ', 
  'Red Anemone'],
  ['Images/TripReports/Lembeh/Sea-Cucumber-Shrimp.jpg',' ',
   'Sea-Cucumber-Shrimp'],
  ['Images/TripReports/Lembeh/Sea-Cucumber-Shrimp-Pair.jpg',' ',
   'Sea-Cucumber-Shrimp-Pair'],
  ['Images/TripReports/Lembeh/Shrimp-on-Purple-Anemone.jpg',' ', 
  'Shrimp on Purple Anemone'],
  ['Images/TripReports/Lembeh/Skeleton-Shrimp-With-Eggs.jpg',' ', 
  'Skeleton Shrimp With Eggs'],
  ['Images/TripReports/Lembeh/Skunk-Clownfish.jpg',' ', 
  'Skunk Clownfish'],
  ['Images/TripReports/Lembeh/Snowflake-Moray.jpg',' ', 
  'Snowflake Moray'],
  ['Images/TripReports/Lembeh/Solar-Power-Nudibranch.jpg',' ', 
  'Solar Power Nudibranch'],
  ['Images/TripReports/Lembeh/Squat-Anemone-Shrimp.jpg',' ',
   'Squat-Anemone-Shrimp'],
  ['Images/TripReports/Lembeh/Starfish-in-Red.jpg',' ',
   'Starfish-in-Red'],
  ['Images/TripReports/Lembeh/Starfish-Texture.jpg',' ',
   'Starfish-Texture'],
  ['Images/TripReports/Lembeh/Starfish-View-1.jpg',' ',
   'Starfish-View-1'],
  ['Images/TripReports/Lembeh/Starfish-View-2-Macro.jpg',' ',
   'Starfish-View-2-Macro'],
  ['Images/TripReports/Lembeh/Starfish-View-3-Subtlety.jpg',' ',
   'Starfish-View-3-Subtlety'],
  ['Images/TripReports/Lembeh/Starfish-View-4-Shrimp.jpg',' ',
   'Starfish-View-4-Shrimp'],
  ['Images/TripReports/Lembeh/Star-of-Tunicates.jpg',' ',
   'Star-of-Tunicates'],
  ['Images/TripReports/Lembeh/Tambja-gabrielae.jpg',' ',
   'Tambja-gabrielae'],
  ['Images/TripReports/Lembeh/Tiger-Shirmp.jpg',' ',
   'Tiger-Shirmp'],
  ['Images/TripReports/Lembeh/Transparent-Shrimp.jpg',' ', 
  'Transparent Shrimp'],
  ['Images/TripReports/Lembeh/Tunicate-Bouquet.jpg',' ', 
  'Tunicate Bouquet'],
  ['Images/TripReports/Lembeh/Tunicate-Macro.jpg',' ', 
  'Tunicate Macro'],
  ['Images/TripReports/Lembeh/Tunicate-Pair.jpg',' ', 
  'Tunicate Pair'],
  ['Images/TripReports/Lembeh/Tunicates-Galore.jpg',' ',
   'Tunicates-Galore'],
  ['Images/TripReports/Lembeh/Unknown.jpg',' ',
   'Unknown'],
  ['Images/TripReports/Lembeh/Whip-Coral-Shrimp2xx.jpg',' ',
   'Whip-Coral-Shrimp'],
  ['Images/TripReports/Lembeh/Wire-Coral-Macro.jpg',' ', 
  'Wire Coral Macro'],
  ['Images/TripReports/Lembeh/Wonderpus-Octopus.jpg',' ', 
  'Wonderpus Octopus'],
  ['Images/TripReports/Lembeh/Wonderpus-Octopus-2.jpg',' ', 
  'Wonderpus Octopus 2'],
  ['Images/TripReports/Lembeh/Wonderpus-Octopus2xx.jpg',' ',
   'Wonderpus-Octopus'],
  ['Images/TripReports/Lembeh/Big-Eye-Soldierfish.jpg',' ',
   'Big Eye Soldierfish'],
  ['Images/TripReports/Lembeh/Blue-Ring-Octopus.jpg',' ',
   'We were told that this was not the season for Blue Ring Octopus viewing, but we saw three in 36 hours!'],
  ['Images/TripReports/Lembeh/Blue-Ring-Octopus-2.jpg',' ',
   'The Blue Ring Octopus is the size of a small fist.....'],
  ['Images/TripReports/Lembeh/Blue-Ring-Octopus-3.jpg',' ',
   '... and has enough venom (a neuro-toxin) to kill 28 men!'],
  ['Images/TripReports/Lembeh/Box-Crab.jpg',' ',
   'Box Crab'],
  ['Images/TripReports/Lembeh/Broccoli-Coral.jpg',' ',
   'Broccoli Coral'],
  ['Images/TripReports/Lembeh/Nudibranch.jpg',' ',
   'Nudibranch'],
  ['Images/TripReports/Lembeh/Nudibranch-2.jpg',' ', 
  'Nudibranch 2'],
  ['Images/TripReports/Lembeh/Chromodoris-kuniei.jpg',' ',
   'Chromodoris-kuniei'],
  ['Images/TripReports/Lembeh/Cleaner-Shrimp.jpg',' ',
   'Cleaner Shrimp'],
  ['Images/TripReports/Lembeh/Cockatoo-Waspfish.jpg',' ',
   'Cockatoo Waspfish'],
  ['Images/TripReports/Lembeh/Coconut-Octopus.jpg',' ',
   'Coconut Octopus - When he grew tired of our photos, he took two half shells, crawled onto one and pulled the other one on top of him, leaving only his eyes visible.'],
  ['Images/TripReports/Lembeh/Corallimorph-Macro.jpg',' ',
   'Corallimorph Macro'],
  ['Images/TripReports/Lembeh/Crinoid.jpg',' ',
   'You can view a crinoid walking on this youtube video. <br> http://www.youtube.com/watch?v=Ly4wLT2850A'],
  ['Images/TripReports/Lembeh/Crocodile-Flathead.jpg',' ',
   'Crocodile Flathead About two feet long, this fellow clearly bears a resemblance to its namesake.'],
  ['Images/TripReports/Lembeh/Crown-of-Thorns-Starfish.jpg',' ',
   'Crown of Thorns Starfish'],
  ['Images/TripReports/Lembeh/Cushion-Star.jpg',' ',
   'Cushion Star'],
  ['Images/TripReports/Lembeh/Cuttlefish.jpg',' ',
   'Cuttlefish - This little fellow was very curious. He swam to my camera lens several times.'],
  ['Images/TripReports/Lembeh/Feather-Star.jpg',' ',
   'Feather Star'],
  ['Images/TripReports/Lembeh/Filefish.jpg',' ',
   'Filefish'],
  ['Images/TripReports/Lembeh/Fire-Urchin.jpg',' ',
   'Fire Urchin'],
  ['Images/TripReports/Lembeh/Flamboyant-Cuttlefish-Calm.jpg',' ',
   'Flamboyant Cuttlefish Calm'],
  ['Images/TripReports/Lembeh/Flamboyant-Cuttlefish-Agit.jpg',' ',
   'Flamboyant Cuttlefish Agitated'],
  ['Images/TripReports/Lembeh/Flamboyant-Cuttlefish-Very.jpg',' ',
   'Flamboyant Cuttlefish Very Agitate'],
   ['Images/TripReports/Lembeh/Glossodoris-cincta-Nudibran.jpg',' ',
   'The 3,000-plus nudibranch species are well equipped to defend themselves. Not only can they be tough-skinned, bumpy, and abrasive, they also have toxic secretions and stinging cells. A few make their own poisons, but most pilfer from the foods they eat. (National Geographic Website)  The nudibranchs brilliant colors warn other creatures that it is toxic.'],
  ['Images/TripReports/Lembeh/Harlequin-Shrimp.jpg',' ',
   'Harlequin Shrimp'],
  ['Images/TripReports/Lembeh/Hermit-Crab.jpg',' ',
   'Hermit Crab'],
  ['Images/TripReports/Lembeh/Janolus-Nudibranch.jpg',' ',
   'Janolus-Nudibranch'],
  ['Images/TripReports/Lembeh/Long-Nose-Shrimp.jpg',' ',
   'Long Nose Shrimp'],
  ['Images/TripReports/Lembeh/Mantis-Shrimp.jpg',' ',
   'The raptorial claws of the Mantis Shrimp can shoot forward at the speed of a .22 caliber bullet leaving the chamber of a gun.'],
  ['Images/TripReports/Lembeh/Mantis-Shrimp-2.jpg',' ', 
  'Mantis Shrimp 2'],
  ['Images/TripReports/Lembeh/Mantis-Shrimp-3.jpg',' ', 
  'Mantis Shrimp 3'],
  ['Images/TripReports/Lembeh/Mantis-Shrimp-With-Eggs.jpg',' ',
   'Mantis Shrimp With Eggs - Now THIS is a hail Mary shot! We knew this little guy was under a log, but he was hiding. While my dive buddies encouraged him to appear on the other side of the log, he ran my way to hide. Silly boy!'],
  ['Images/TripReports/Lembeh/Map-Puffer.jpg',' ',
   'Map Puffer'],
  ['Images/TripReports/Lembeh/Network-Pipefish.jpg',' ',
   'Pipefish look like straight-bodied seahorses with tiny mouths.  Many are weak swimmers, moving slowly by means of rapid movements of the dorsal fin'],
  ['Images/TripReports/Lembeh/One-Inch-Pygmy-Seahorse-.jpg',' ',
   'One Inch Pygmy Cuttlefish - How do these dive guides find these creatures. This Pygmy Cuttlefish is just 1" in length. Divemaster, Johnnie, my hero!'],
  ['Images/TripReports/Lembeh/Ornate-Ghost-Pipefish.jpg',' ',
   'Ornate Ghost Pipefish'],
  ['Images/TripReports/Lembeh/Painted-Frogfish.jpg',' ',
   'Painted Frogfish - Just an inch in size'],
  ['Images/TripReports/Lembeh/Porcelain-Crab.jpg',' ',
   'Porcelain Crab'],
  ['Images/TripReports/Lembeh/Pygmy-Seahorse.jpg',' ',
   'Hippocampus bargibanti - This Pygmy Seahorse is the size of a piece of long-grain rice. Barely visible to my eyes, this is another Hail Mary shot.'],
  ['Images/TripReports/Lembeh/Rare-White-Halimeda-Ghost-P.jpg',' ',
   'Halimeda Ghost Pipefish - Generally green in color, this white Halimeda is a rare find.'],
  ['Images/TripReports/Lembeh/Siagiani-Hairy-Squat-Lobste.jpg',' ',
   'Siagiani Hairy Squat Lobster - Another creature almost too small to see - fingertip size.'],
  ['Images/TripReports/Lembeh/Spiny-Devilfish.jpg',' ',
   'Spiny Devilfish'],
    ['Images/TripReports/Lembeh/Tube-Anemone.jpg',' ',
   'Tube Anemone'],
  ['Images/TripReports/Lembeh/Tunicate-Rainbow.jpg',' ',
   'A Rainbow of Tunicates - Tunicates are marine animals that have a cylindrical or globular body and a rubbery or hard outer coat and two siphons to draw water into and out of the body.'],
  ['Images/TripReports/Lembeh/Tyroli-Nudibranch.jpg',' ',
   'Tyroli Nudibranch'],
  ['Images/TripReports/Lembeh/Warty-Frogfish.jpg',' ',
   'Warty Frogfish'],
  ['Images/TripReports/Lembeh/Anemone2.jpg',' ',
   'Anemone'],
  ['Images/TripReports/Lembeh/Clark-Anemonefish.jpg',' ',
   'This little fellow is peeking out from his anemone home, checking for danger before emerging.'],
  ['Images/TripReports/Lembeh/Clown-Anemonefish.jpg',' ',
   'Clown Anemonefish'],
  ['Images/TripReports/Lembeh/Filefish2.jpg',' ',
   'Filefish'],
  ['Images/TripReports/Lembeh/Filefish-Color-Change.jpg',' ',
   'Filefish Color Change'],
  ['Images/TripReports/Lembeh/Filefish-D.jpg',' ',
   'Filefish D'],
  ['Images/TripReports/Lembeh/Giant-Frogfish.jpg',' ',
   'Giant Frogfish'],
  ['Images/TripReports/Lembeh/Goby-on-Whip-Coral.jpg',' ',
   'Goby on Whip Coral'],
  ['Images/TripReports/Lembeh/Intermediate-Lionfish.jpg',' ',
   'Intermediate Lionfish'],
  ['Images/TripReports/Lembeh/Juvenile-Banggai-Cardinalfish.jpg',' ',
   'Juvenile Banggai Cardinalfish'],
  ['Images/TripReports/Lembeh/Juvenile-Lionfish.jpg',' ',
   'Juvenile Lionfish'],
  ['Images/TripReports/Lembeh/Mottled-Filefish.jpg',' ',
   'Mottled Filefish'],
  ['Images/TripReports/Lembeh/Shaggy-Frogfish.jpg',' ',
   'Shaggy Frogfish'],
  ['Images/TripReports/Lembeh/Skunk-Anemonefish-Scene.jpg',' ',
   'Skunk Anemonefish Scene'],
  ['Images/TripReports/Lembeh/Warty-Frogfish2.jpg',' ',
   'Warty Frogfish'],
  ['Images/TripReports/Lembeh/Wrasse.jpg',' ',
   'Wrasse'],
  ['Images/TripReports/Lembeh/Yellow-Shaggy-Frogfish.jpg',' ',
   'Yellow Shaggy Frogfish'],
  ['Images/TripReports/Lembeh/Whip-Coral-Shrimp.jpg',' ',
   'Whip Coral Shrimp'],
  ['Images/TripReports/Lembeh/Black-Saddled-Snake-Eel.jpg',' ',
   'Black Saddled Snake Eel'],
  ['Images/TripReports/Lembeh/Black-Saddled-Snake-Eel-2.jpg',' ',
   'Black Saddled Snake Eel 2'],
   ['Images/TripReports/Lembeh/Black-Saddled-Snake-Eel-Wit.jpg',' ',
   'Black Saddled Snake Eel With Fish'],
  ['Images/TripReports/Lembeh/Black-Spotted-Puffer.jpg',' ',
   'Black Spotted Puffer'],
  ['Images/TripReports/Lembeh/Ceratosoma.jpg',' ',
   'Ceratosoma'],
  ['Images/TripReports/Lembeh/Chromodoris-Juvenile.jpg',' ',
   'Chromodoris Juvenile'],
   ['Images/TripReports/Lembeh/Chromodoris-Rudiani.jpg',' ',
   'Chromodoris Rudiani'],
  ['Images/TripReports/Lembeh/Dragonet.jpg',' ',
   'If you are having trouble making out this creature, look for his eye and his red mouth at the right.'],
  ['Images/TripReports/Lembeh/Fibriated-Moray.jpg',' ',
   'Fibriated Moray'],
  ['Images/TripReports/Lembeh/Humpback-Scorpionfish.jpg',' ',
   'Humpback Scorpionfish'],
   ['Images/TripReports/Lembeh/Humpback-Scorpionfish-Face.jpg',' ',
   'Humpback Scorpionfish Face'],
  ['Images/TripReports/Lembeh/Juvenile-Snapper.jpg',' ',
   'Juvenile Snapper'],
  ['Images/TripReports/Lembeh/Mandarinfish.jpg',' ',
   'The Mandarin Fish is 1-2 inches in length.  It is one of only two animal species known to have blue coloring.  Each evening, within 20 minutes of sunset, groups of three to five females gather.  Males visit and display courtship behavior, hoping to attract females.'],
  ['Images/TripReports/Lembeh/Map-Puffer-Face.jpg',' ',
   'Map Puffer Face'],
   ['Images/TripReports/Lembeh/Map-Puffer-With-Eggs.jpg',' ',
   'Map Puffer With Eggs'],
  ['Images/TripReports/Lembeh/Napoleon-Snake-Eel.jpg',' ',
   'Napoleon Snake Eel'],
   ['Images/TripReports/Lembeh/Puffer.jpg',' ',
   'Puffer'],
  ['Images/TripReports/Lembeh/Razorfish.jpg',' ',
   'Razorfish'],
   ['Images/TripReports/Lembeh/Ribbon-Eel.jpg',' ',
   'Ribbon Eel'],
  ['Images/TripReports/Lembeh/Ribbon-Eel-Juvenile.jpg',' ',
   'Ribbon Eel Juvenile'],
  ['Images/TripReports/Lembeh/Sea-Snake.jpg',' ',
   'Sea Snake'],
  ['Images/TripReports/Lembeh/Snapper-Juvenile.jpg',' ',
   'Snapper Juvenile'],
   ['Images/TripReports/Lembeh/Spiny-Devilfish-Face.jpg',' ',
   'Spiny Devilfish Face'],
  ['Images/TripReports/Lembeh/Spotted-Sweetlips.jpg',' ',
   'Spotted Sweetlips'],
  ['Images/TripReports/Lembeh/Stargazer.jpg',' ',
   'The Stargazer is a fish that hides below the sand with just its eyes visible.  Our dive guide fanned the sand to reveal his body.'],
  ['Images/TripReports/Lembeh/Stargazer-Burrowing.jpg',' ',
   'Not appreciating our intrusion, he wiggled back into the sand.  As he settled below the sand, he began to put out his lure; seen here in partial presentation.'],
  ['Images/TripReports/Lembeh/Stargazer-Buried-With-Lure-.jpg',' ',
   'Now buried with lure fully exposed and ready to tempt his prey, he waits.'],
  ['Images/TripReports/Lembeh/Toby.jpg',' ',
   'Toby'],
  ['Images/TripReports/Lembeh/Unknown-Fish.jpg',' ',
   'Unknown Fish'],
  ['Images/TripReports/Lembeh/Wonderpus-Octopus.jpg',' ',
   'Wonderpus Octopus']
  ]

function slideshow(slide_num) {
  document.getElementById('mypic').src=imgArray[slide_num][0];
  document.getElementById('mypic').alt=imgArray[slide_num][1];
  document.getElementById('burns').innerHTML=imgArray[slide_num][2];
}

function slideshowUp() {
  num++;
  num = num % imgArray.length;
  slideshow(num);
}

function slideshowBack() {
  num--;
  if (num < 0) {num=imgArray.length-1;}
  num = num % imgArray.length;
  slideshow(num);
}
// JavaScript Document